export const REQUEST_PRODUCTS_LIST = 'REQUEST_PRODUCTS_LIST';
export const SUCCES_REQUEST_PRODUCTS_LIST = 'SUCCES_REQUEST_PRODUCTS_LIST';
export const ERROR_REQUEST_PRODUCTS_LIST = 'ERROR_REQUEST_PRODUCTS_LIST';

export const REQUEST_POPULAR_LIST = 'REQUEST_POPULAR_LIST';
export const SUCCES_REQUEST_POPULAR_LIST = 'SUCCES_REQUEST_POPULAR_LIST';
export const ERROR_REQUEST_POPULAR_LIST = 'ERROR_REQUEST_POPULAR_LIST';